version: "3"

services:
  bot:
    image: matrixarcher/solana-smart-signal:latest
    # ports:
    #   - "8080:80"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    # networks:
    #   - mynetwork
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TIMEZONE=${TIMEZONE}
      - CHANNEL_ID=${CHANNEL_ID}
      - ADMIN_LIST=${ADMIN_LIST}
      - PRIVATE_KEY_BASE58_LIST=${PRIVATE_KEY_BASE58_LIST}
      - WALLET_ADDRESS_LIST=${WALLET_ADDRESS_LIST}
